baseURL = "https://h4xk0r.github.io/"
languageCode = "zh-cn"
title = "H4ck3r Station"
theme = "PaperMod"

# 禁用 RSS 以彻底避开 PaperMod 旧模板变量报错
[outputs]
    home = ["HTML", "JSON"]

[params]
    # 新版 Hugo 要求的作者格式
    author = "h4xk0r" 
    
    mainSections = ["posts"]
    defaultTheme = "dark"
    ShowCodeCopyButtons = true
    ShowReadingTime = true
    ShowSearchButton = true
    
    # 目录配置
    ShowToc = true          
    TocOpen = true          

    [params.homeInfoParams]
        Title = "Security Documentation"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/h4xk0r"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "档案"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "搜索"
        url = "/search/"
        weight = 20
    [[menu.main]]
        name = "分类"
        url = "/categories/"
        weight = 30

[taxonomies]
    category = "categories"
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    startLevel = 2
    endLevel = 4