baseURL = "https://h4xk0r.github.io/"
languageCode = "zh-cn"
title = "H4ck3r Station"
theme = "PaperMod"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    # 1. 先放普通参数 (保证 ToC 能够被正确解析)
    mainSections = ["posts"]
    defaultTheme = "dark"
    ShowCodeCopyButtons = true
    ShowReadingTime = true
    ShowSearchButton = true
    
    # 目录配置放在这里最稳妥
    ShowToc = true          
    TocOpen = true          

    # 2. 再放子层级参数
    [params.homeInfoParams]
        Title = "Security Documentation"

    # 3. 最后放数组类参数 (socialIcons 必须放在 params 区块的最后)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/h4xk0r"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "档案"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "搜索"
        url = "/search/"
        weight = 20

[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    startLevel = 2
    endLevel = 4